edition = "2024"
style_edition = "2024"

wrap_comments = true
format_code_in_doc_comments = true
comment_width = 120
doc_comment_code_block_width = 120
normalize_comments = true

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
